### ISSUE TITLE
what does 'pol_shift' mean?

### ISSUE THREAD

**Issue by zacario-li** [NikolasEnt/Advanced-Lane-Lines#3]
Hi, Nikolas,  
    I saw you use 'pol_shift' in your code, but I don't know what does these codes do? Could you help me?
`left_fit = pol_shift(left_fit_p,-SPEED)*(1.0-len(x)/((1.0-RANGE)*IMAGE_H))+left_fit*(len(x)/((1.0-RANGE)*IMAGE_H))`

**Comment by NikolasEnt** [comment]
Hi, @zacario-li,
the code  smooth two consecutive polynomials of the line fit (the detection on the previous frame and on the current one). It helps to reduce noise of predicted lane lines - especially it helps to smooth jitter of the far end of the line in case of a high order polynomial fit.

**Comment by NikolasEnt** [comment]
BTW, you may find useful in your study my web site with some explanation on the project https://nikolasent.github.io/proj/proj1
