### ISSUE TITLE
How to calculate the coefficients about thres_l_calc?

### ISSUE THREAD

**Issue by zacario-li** [NikolasEnt/Advanced-Lane-Lines#4]
Hi Nikolas,
    what does these func mean? How to calculate the coefficients 
`thres = -0.0045*sens**2+1.7581*sens-115.0`
# Calculate threashold for left line
>
def thres_l_calc(sens):  
    thres = -0.0045*sens**2+1.7581*sens-115.0  
    if thres < 25*(382.0-sens)/382.0+5:  
        thres = 25*(382.0-sens)/382.0+5  
    return thres  
  
# Calculate threashold for right line
>  
def thres_r_calc(sens):  
    thres = -0.0411*sens**2+9.1708*sens-430.0  
    if sens<210:  
        if thres < sens/6:  
            thres = sens/6  
    else:  
        if thres < 20:  
            thres = 20  
    return thres

**Comment by NikolasEnt** [comment]
Hi, @zacario-li, it is a second order polynomial fit of manually selected thresholds for different levels of 'sens'. I examined about 10-20 points in different lighting conditions and manually select thresholds for them.
